// 像素图标集：16x16 字符画 + 调色板，与角色包同一画风
// '.' = 透明；每格字符映射调色板色
export const PALETTE = {
  K: '#3a3a44', // 描边深灰
  P: '#7c6cf0', // 主紫
  D: '#4b3ec2', // 深紫
  W: '#ffffff', // 白
  B: '#b9b9c5', // 浅灰
  R: '#f76a8c', // 粉
  r: '#d94f70', // 深粉
  Y: '#ffd75e', // 黄
  O: '#ff9f43', // 橙
  U: '#8ec9ff', // 浅蓝
  u: '#5aa7e8', // 蓝
  G: '#909090', // 鸽子灰
  g: '#6e6e78' // 深鸽灰
}

export const ICONS = {
  mic: [
    '................',
    '......KKKK......',
    '....KKWWWWKK....',
    '...KWWWBWWWWK...',
    '...KWBWWWWWWK...',
    '...KWWWWWWWWK...',
    '...KWWWWWWWWK...',
    '....KWWWWWWK....',
    '.....KWWWWK.....',
    '......KWWK......',
    '......KWWK......',
    '...KKKKWWKKKK...',
    '..KBK..WW..KBK..',
    '..KB...WW...KB..',
    '.......WW.......',
    '.....KKWWKK.....'
  ],
  heart: [
    '................',
    '................',
    '...KKKK.KKKK....',
    '..KRRRRKRRRRK...',
    '.KRRRRRRRRRRRK..',
    '.KRWRRRRRRRRrK..',
    '.KRRRRRRRRRRrK..',
    '.KRRRRRRRRRRrK..',
    '..KRRRRRRRRrK...',
    '...KRRRRRRrK....',
    '....KRRRRrK.....',
    '.....KRRrK......',
    '......KrK.......',
    '.......K........',
    '................',
    '................'
  ],
  note: [
    '................',
    '........KKKKK...',
    '........KPPPPK..',
    '........KPPPPK..',
    '........KPPPPK..',
    '........KPPPPK..',
    '........KPPPPK..',
    '........KPPPK...',
    '........KPPK....',
    '........KPK.....',
    '...KKKKKPK......',
    '..KPPPPPK.......',
    '.KPPPPPPK.......',
    '.KPPPPPK........',
    '..KKKKK.........',
    '................'
  ],
  zzz: [
    '................',
    '.......KKK......',
    '.......KBK......',
    '........BK......',
    '.......BK.......',
    '.......KBBK.....',
    '.......KKK......',
    '................',
    '..KKK...........',
    '..KBK...........',
    '...BK...........',
    '..BK............',
    '..KBBBK.........',
    '..KKKK..........',
    '................',
    '................'
  ],
  spark: [
    '................',
    '.......KK.......',
    '......KYYK......',
    '......KYYK......',
    '.......KYK......',
    '..KK..KYYK..KK..',
    '..KYKKYYYYKKYK..',
    '...KYYYWWYYYK...',
    '....KYWWWWYK....',
    '...KYYYWWYYYK...',
    '..KYKKYYYYKKYK..',
    '..KK..KYYK..KK..',
    '.......KYK......',
    '......KYYK......',
    '......KYYK......',
    '.......KK.......'
  ],
  chat: [
    '................',
    '................',
    '..KKKKKKKKKKKK..',
    '.KPPPPPPPPPPPPK.',
    '.KPPDKPPDKPPPPK.',
    '.KPPDKPPDKPPPPK.',
    '.KPPPPPPPPPPPPK.',
    '.KPPPPPPPPPPPPK.',
    '..KPPPPPPPPPPK..',
    '...KPPPPPPPPK...',
    '....KPPPPPPK....',
    '.....KPPPPK.....',
    '......KPPK......',
    '.......KK.......',
    '................',
    '................'
  ],
  hot: [
    '................',
    '..KKKKKKKKKK....',
    '..KWWWWWWWWK....',
    '..KWDDWDDWWK....',
    '..KWWWWWWWWK....',
    '..KWWWWWWWWK....',
    '..KWKKKKKKWK....',
    '..KWWWWWWWWK....',
    '..KWKKKKKWWK....',
    '..KWWWWWWWKK....',
    '..KWWWWWWK......',
    '..KWWWWWK.......',
    '..KWWWWK........',
    '..KWWWWK........',
    '...KKKK.........',
    '................'
  ],
  rain: [
    '................',
    '....KKKKK.......',
    '...KBBBBBK......',
    '..KBBBBBBBKK....',
    '..KBBBBBBBBBK...',
    '..KBBBBBBBBBK...',
    '...KKKKKKKKK....',
    '................',
    '....U...U...U...',
    '...U.U.U.U.U.U..',
    '................',
    '....u...u...u...',
    '...u.u.u.u.u.u..',
    '................',
    '................',
    '................'
  ],
  walk: [
    '................',
    '................',
    '...K.K.K........',
    '...K.K.K........',
    '..KPKKPKPK......',
    '..KPPPPPPK......',
    '...KPPPPK.......',
    '....KKKK........',
    '................',
    '........K.K.K...',
    '........K.K.K...',
    '.......KPKKPKPK.',
    '.......KPPPPPPK.',
    '........KPPPPK..',
    '.........KKKK...',
    '................'
  ],
  bird: [
    '................',
    '.....KKKK.......',
    '....KGGGGK......',
    '...KGGGGGGK.....',
    '..KGGKWGGGGK....',
    '..KGGKWGGGGK....',
    '..KGGGGGGGGK....',
    '..KGGGGGGGGK....',
    '..KGGGGGGGKKK...',
    '...KGGGGKOOOK...',
    '...KGGGGKOK.....',
    '....KGGGGK......',
    '.....KKKK.......',
    '................',
    '................',
    '................'
  ],
  sun: [
    '................',
    '.......KK.......',
    '.......KYK......',
    '.......KYK......',
    '.K.....KYK....K.',
    '.KK...KYYYK..KK.',
    '..KK.KYYYYK.KK..',
    '...KKYYWYYYKK...',
    '....KYWWWYYK....',
    '...KKYYWWYYYKK..',
    '..KK.KYYYYK.KK..',
    '.KK...KYYK...KK.',
    '.K.....KYK.....K',
    '.......KYK......',
    '.......KYK......',
    '.......KK.......'
  ],
  gear: [
    '................',
    '....KK..KK......',
    '...KDKKKKDK.....',
    '....KDDDDK......',
    '..KKDDWWDDKK....',
    '.KDDDWWWWDDDK...',
    '.KDDWWDDWWDDK...',
    'KKDDWDDDDDWDDKK.',
    'KDDWWDDDDDWWDDK.',
    'KDDWDDDDDDDWDDK.',
    '.KDDWWDDWWDDK...',
    '.KDDDWWWWDDDK...',
    '..KKDDWWDDKK....',
    '....KDDDDK......',
    '...KDKKKKDK.....',
    '....KK..KK......'
  ],
  qr: [
    '................',
    '.KKKKKKKKKKK....',
    '.KWWWKWWWKWK....',
    '.KWKWKWKKKWK....',
    '.KWWWKWWWKWK....',
    '.KKKKKKKKKKK....',
    '.KWKKKWKWKKK....',
    '.KKKWKWWKWWK....',
    '.KWWKKWKKWKK....',
    '.KKKKKKKKKKK....',
    '.KWWKWWWKWKW....',
    '.KWKKWKKWKWK....',
    '.KWWWKWWKKKK....',
    '.KKKKKKKKKKK....',
    '................',
    '................'
  ],
  power: [
    '................',
    '.......KK.......',
    '.......KK.......',
    '.......KK.......',
    '....KKK..KKK....',
    '...KK......KK...',
    '..KK........KK..',
    '..K....KK....K..',
    '..K....KK....K..',
    '..K..........K..',
    '..K..........K..',
    '..KK........KK..',
    '...KK......KK...',
    '....KKK..KKK....',
    '.....KKKKKK.....',
    '................'
  ]
}
